### ISSUE TITLE
Copying parameters between ninjax modules

### ISSUE THREAD

**Issue by jren03** [danijar/ninjax#12]
Hello, I have a question as to how I could copy parameters over from one `nj.Module` to another? For example, I would probably have something like the following if I were using Flax:

```
def _copy_params(old_network_params, new_network_params):
    """
    Copies from old_network_params to new_network_params recursively.
    If a key exists in new_network_params but not in old_network_params, it is skipped.
    """
    new_params = {}
    for key, value in new_network_params.items():
        if key in old_network_params:
            if isinstance(value, dict):
                new_params[key] = _copy_params(old_network_params[key], value)
            elif old_network_params[key].shape == value.shape:
                new_params[key] = old_network_params[key]
            else:
                new_params[key] = value
        else:
            new_params[key] = value
    return FrozenDict(new_params)

copied_params = _copy_params(old_network.params, new_network.params)
new_network = TrainState.create(apply_fn=new_network.apply_fn, params=copied_params, tx=tx)
```

I'm not too sure how to access the params in an `nj.Module` object though. It seems like this is doable through the `put()` function, but I'm unable to access the parameter values through the `get()` function.

**Comment by danijar** [comment]
Hi, does `nj.Module.find(pattern=r'.*', empty_ok=False)` so what you want:

```
dest.put(source.find())
```

I'm a bit confused with your example though because it's not self-contained. There is generally no need to copy JAX arrays because they are immutable.

Ninjax also uses a param dict instead of a param tree so you can iterate over it more easily. It does support trees through for interoperability with the ecosystem, e.g. Flax.
