### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [danijar/ninjax#4]
Thanks for a cool project. Im not sure if its just stockholm syndrome that I have come to prefer a more explicitly pure style for many operations; but at the same time I feel there are design patterns which a pure functional style has not found good design patterns for, like collecting activation losses through a network; and it seems something like ninjax is the way to go.

Some critical questions, if you dont mind:

- Do you find there are limitations on functionality, such as imperfect composability for ninjaxified JAX-like operations, compared to their native JAX variants?
- Do you find there is a significant impact on compilation time in using ninjax?
- For sure, this extra abstraction layer probably wont help with JAX already less-than-stellar clarity of its error messages?
- Are there any other steelman-arguments against the purify pattern, that you are aware of?
- I like the global rng stuff; frankly I have yet to work on an application where the greater control that JAX gives you over rng state was worth the extra effort; but technically at least, I suppose there is the downside, that now the order of your rng operations are only as deterministic as your python interpreter/jax compiler; and if theyd do any internal multithreading (i dont think they do now?) that changes the order of rng calls, results need not be deterministic across different compilation runs?
- I think im pretty happy with the linen/optax model where my params / optimizer state are not coupled to my model definition and I dont know that id want that to become more OOP/torch-like (though its cool that we have the option). I suppose there is no argument against dipping my toes into ninjax by just replacing my rng handling first, without taking the full ninjax-pill?

**Comment by danijar** [comment]
Hey!

> Do you find there are limitations on functionality, such as imperfect composability for ninjaxified JAX-like operations, compared to their native JAX variants?

The same as with other frameworks here. JAX transformations like grad, cond, and while except pure functions as inputs. If you want to pass an impure user function into something like JAX grad or while then you have to purify it first. Ninjax and other frameworks thus also provide their own versions of grad and while that does this for you. That lets you use grad and while inside impure functions. Internally, those wrappers take the param tree out of the global variable, pass them into the JAX grad/while/etc, and then put them back into the global variable before calling the user function.

> Do you find there is a significant impact on compilation time in using ninjax?

99%+ of compilation time happens in XLA after the program graph has been created. So there is no overhead from Ninjax.

> For sure, this extra abstraction layer probably wont help with JAX already less-than-stellar clarity of its error messages?

Yes, it doesn't help (and also doesn't hurt).

> Are there any other steelman-arguments against the purify pattern, that you are aware of?

I see function transformations and functional programming as the right choice for a low-level deep learning framework like JAX. That said, I don't think it's productive to implement learning algorithms at that level, so there is a need for higher-level libraries that introduce state. All those libraries need some form of purify transformation. In Haiku it's called `hk.transform` and Flax attaches its transformed init/apply functions automatically onto each module.

Haiku deserves credit as one of the first libraries that implement state for JAX but I think it's using an overly complicated and overly restrictive approach. Flax came later and is easier to use but I think it's over-engineered and also overly restrictive (far from the "flexible" in its tag line). Both Haiku and Flax are perfectly fine when you train a single neural network with a single function end-to-end, but they aren't suited for more complex use cases.

> I like the global rng stuff; frankly I have yet to work on an application where the greater control that JAX gives you over rng state was worth the extra effort; but technically at least, I suppose there is the downside, that now the order of your rng operations are only as deterministic as your python interpreter/jax compiler; and if theyd do any internal multithreading (i dont think they do now?) that changes the order of rng calls, results need not be deterministic across different compilation runs?

The order in which the RNG is split is purely determined by the Python program. XLA optimizations don't affect it because everything is functional at that point. You're also safe in multithreaded environments. Each thread can runs its own (or the same) pure/jitted function because the RNG is only global **within** each pure/jitted function. You would run into issues if you used multithreading **inside** of a jitted function but that makes no sense anyways. So everything is deterministic despite global RNG.

But as you said, for some algorithms it's better to manually split an RNG key. In that case, you can either just pass the RNG as a normal input argument to the impure JAX function, or you can use `nj.rng()` early in your impure JAX function and then pass that into your inner functions.

> I think im pretty happy with the linen/optax model where my params / optimizer state are not coupled to my model definition and I dont know that id want that to become more OOP/torch-like (though its cool that we have the option). I suppose there is no argument against dipping my toes into ninjax by just replacing my rng handling first, without taking the full ninjax-pill?

Params and optimizer state aren't coupled to your model object in Ninjax either. This is same in most frameworks that add state to JAX. At a high level, you pass the params tree into the purified function, and what the purify wrapper does is put the param tree into a global variable. You modules can then read from (and in Ninjax also write into) that global param tree. After running your impure user function, the purify wrapper takes the param tree back out of the global variable and returns it as a return value, so everything looks pure from the perspective of JAX and can be transformed with jit etc.

**Comment by EelcoHoogendoorn** [comment]
> wrt flax/haiku

Agreed, it is also my initial impression that the purify mechanism as implemented here in ninjax is a more general, and in its generality imo the more comprehensible abstraction than the terminology introduced by flax/haiku. Frankly I had never really committed to trying to understand what they were doing under the hood; but reading the ninjax readme and source made it click for me in a fraction of the time id spent on trying to understanding those others.

What you are saying sounds convincing to me; sometimes there isnt a good reason it hasnt been done before.

**Comment by danijar** [comment]
I agree it would be cool for JAX to support a very basic state mechanism. That way, frameworks don't have to wrap all the native JAX transformations. On the other hand, of course there is a risk in committing to a specific design (and the additional complexity) for JAX if there isn't agreement on what the best design is.

I haven't seen the specific design used in Ninjax anywhere else, it was just inspired by how Haiku and Flax work. I might sit down with the JAX team at some point to talk this through.

**Comment by EelcoHoogendoorn** [comment]
I suppose one of the core questions would be if you could make a clean cut between a generic context capturing and purifying mechanism, and more module / naming composition related specifics which do not feel like theyd belong in JAX; not sure to what extent that would be possible or desirable.

**Comment by danijar** [comment]
I think that's very possible. Ninjax uses this separation, the first ~300 lines of ninjax.py implement purify, accessing/modifying the global state, and the impure version of standard JAX transformations. The remaining ~200 lines implement scopes and modules on top of that.
